### PR TITLE
Added Franken Gateway fff-gw-m1

### PR DESCRIPTION
**Pull request by mayosemmel**

### CODE REVIEW

**Comment by Ranlvor** [comment]
Checking franken_fff-gw-m1
     2a03:4000:6:b083::1 port 655/udp is closed
     37.120.190.92 port 655/udp is closed

Läuft der tinc?

**Comment by mayosemmel** [comment]
The Name with - except of _ was invalid. Because of this the Tinc alway failed to start.

**Comment by Ranlvor** [comment]
Checking franken_fff_gw_m1
     2a03:4000:6:b083::1 port 655/udp is closed
     37.120.190.92 port 655/udp is closed

still the same

**Comment by mayosemmel** [comment]
Yes, I'm Sorry. The Tinc was running now, but the Port is 656. Now it should work.

**Comment by Ranlvor** [comment]
Ok. Looks good to me. *merge*

Could you take another look at freifunk/icvpn-meta#262?

**Pull request merged**
