### PR TITLE
vpn7.freifunk.in-kiel.de

### PR DESCRIPTION
**Pull request by fsteinel**
add vpn7.freifunk.in-kiel.de

### CODE REVIEW

**Comment by Ranlvor** [comment]
```
Checking kiel7
 176.9.127.35 port 655/udp is closed
```
Bitte nochmal melden wenn der Tinc läuft

**Comment by Ranlvor** [comment]
Timeout: TODO: schließen am 01.02.2017

**Comment by fsteinel** [comment]
Opened Port, howto recheck?

**Comment by Ranlvor** [comment]
The build was successfully restarted.

**Comment by mweinelt** [comment]
```
Nmap scan report for vpn7.freifunk.in-kiel.de (176.9.127.35)
Host is up (0.023s latency).
PORT    STATE  SERVICE
655/udp closed tinc
```

**Comment by Ranlvor** [comment]
```
Checking kiel7
 176.9.127.35 port 655/udp is closed
```

**Comment by fsteinel** [comment]
That odd.
```
grill@somewhere:~/$ netcat vpn7.ffki.de 656
0 kiel7 17
```
I'm testing if tcp and udp is working and report back.

**Comment by Ranlvor** [comment]
Just noticed: You test on a different port than our test. Having no port in the configuration is interpreted as using the default-port of 655. You are trying on port 656.

**Comment by fsteinel** [comment]
Thanks for the hint 😄

**Comment by Ranlvor** [comment]
```
Checking kiel7
 176.9.127.35 port 656/udp is open|filtered
```

**Pull request merged**
