### PR TITLE
Added host hannover1.

### PR DESCRIPTION
**Pull request by lemoer**

### CODE REVIEW

**Comment by leeps** [comment]
You're missing at least the
```address =```
line.

Try again.

**Comment by lemoer** [comment]
Our router is currently just for testing purpose and stands behind a nat.

I will add an address when it's in production mode.

**Comment by Ranlvor** [comment]
You could do a port-forwarding for tinc to allow to be accessed from outside

**Comment by lemoer** [comment]
It's currently just a virtual machine on my laptop with changing public ip-address...

Is it possible to test it this way?

**Comment by Ranlvor** [comment]
Well, ok. How about a time-limit: you get the entry without a hostname for 1 month, if there is no hostname after 1 month we delete the entry.

**Comment by lemoer** [comment]
Thanks

**Pull request merged**
