### PR TITLE
Create cottbus1

### PR DESCRIPTION
**Pull request by marcel-sch**
cottbus1 was created

### CODE REVIEW

**Comment by Ranlvor** [comment]
Just rerun the test. It still says

    Checking cottbus1
     2001:41d0:52:d00::1626 port 655/udp is closed
     151.80.155.239 port 655/udp is closed

Is the tinc already running?

**Comment by marcel-sch** [comment]
I restartet the service. Service is using port 655

**Comment by Ranlvor** [comment]
*rebuild*

**Comment by Ranlvor** [comment]
Checking cottbus1
     2001:41d0:52:d00::1626 port 655/udp is open|filtered
     151.80.155.239 port 655/udp is open|filtered

looks fine to me *merge*

**Comment by Ranlvor** [comment]
cottbus1 now has layer2-connectivity but the bgp-deamon seems not to work: „Socket: Connection refused“

**Comment by marcel-sch** [comment]
setup of bgp is on process, we are still learning

**Comment by Ranlvor** [comment]
ok. Good luck, have fun. Learning is great.

**Pull request merged**
