### PR TITLE
Großreinemachen

### PR DESCRIPTION
**Pull request by kpanic23**
Removed all hosts offline for at least 14 days. Tested via ping and
telnet to tinc port.

### CODE REVIEW

**Comment by mweinelt** [comment]
I'm very inclined to accepting this pull request, as it will severly cut down on the L2 ARP/NDP abuse that is regularly happening on the transfer network, that pushes our tinc instances to the CPU cap.

Let's put a heads-up on the mailing list and recheck if any of those peers turn up again on/until(?) 2017-08-13.

CC @Ranlvor

**Comment by ddmesh** [comment]
Hi, I don't like to have Dresden being removed. I know it is offline since long (because internal server restructuring). But when we connect to icvpn later again, I need server accepting connections. When I then have to create a new pull request which takes a while until it is merged in to git repository and then wait some other weeks to have icvpn server updating their configs, it is very likely that we'll give up connecting to icvpn.
I can not tell when we will get connected to icvpn, but surely not within next two or more month.
Bye Stephan (Freifunk Dresden)

**Comment by rubo77** [comment]
So I suggest to let Dresden be put on a **list** with communities, that are not being removed then. Everybody who reacts and wants to stay, although inactive, can be added to that list here.

**Comment by wusel42** [comment]
I strongly agree with @mweinelt to move this to the mailing list.

@ddmesh: a time frame of "two or more months" is quite something. As there are several communities that do have automated their ICVPN setup, I don't see the issue of adding Dresden's servers a few days before of finally getting ready?

**Comment by wusel42** [comment]
Is there a flaw in the method?

bgp1.guetersloh.freifunk.net certainly is alive and kicking (well, it's tinc, so ... it's more undead than alive):

root@bgp1:~# netstat -antp | grep tinc
tcp        0      0 0.0.0.0:655             0.0.0.0:*               LISTEN      4941/tincd      
tcp        0      0 192.251.226.114:51375   82.195.73.48:655        ESTABLISHED 4941/tincd      
tcp        0      0 192.251.226.114:36354   213.128.138.161:655     ESTABLISHED 4941/tincd      
tcp        0      0 192.251.226.114:655     188.165.145.158:35346   ESTABLISHED 4941/tincd      
tcp        0      0 192.251.226.114:655     77.87.49.4:53696        ESTABLISHED 4941/tincd      
tcp6       0      0 :::655                  :::*                    LISTEN      4941/tincd      

Just curious.

**Comment by mweinelt** [comment]
Just seen reachable:
- amsterdam1
- kreisgt_bgp1

**Comment by wusel42** [comment]
Ignore kreisgt_bgp1(see PR). (My point in bringing this up was that bgp1 was still active, although named dead in this PR.)

**Comment by skorpy2009** [comment]
What is the status on this?

**Comment by mweinelt** [comment]
Rebased and merged.

**Pull request closed without merging**
